---
title: "BUSMKT 1481-1060 Brand Management"
subtitle: "Syllabus Fall 2022"
author: "Mike Nguyen"
date: "`r Sys.Date()`"
output:
  pdf_document: 
    number_sections: true
    toc: true
  html_notebook: 
    number_sections: true
urlcolor: blue
bibliography: references.bib
---

\newpage

Instructor: Mike Nguyen

Office: 249

Email: [mikenguyen\@pitt.edu](mailto:mikenguyen@mail.missouri.edu){.email}

Class Hours: 6:30 PM - 9:00 PM (Monday) 08/29/2022 - 12/17/2022

Classroom: 201 Mervis Hall

Office Hours: [by appointment](https://calendly.com/mikenguyenbio)

# Textbooks

Strategic Brand Management[**, *5th edition, Kevin Keller & Vanitha Swaminathan***]{.underline} The materials for this course are delivered online by Pearson.

<br>

# Objectives

## Course Objectives

The Brand Management course will benefit prospective brand and product managers, as well as marketing-minded managers. The course examines how brands influence customer choices and how to manage them. As organizations have purchased or grown brand assets, they've realized that branding is challenging. Since branding success is both an art and science, there is hardly ever a "right" strategy for a branding problem. This course will attempt to provide a comprehensive understanding and discussion of important theories and models, as well as toolkit that is available at the brand manager's disposal. However, an "optimal" solution will ultimate depend on the manager's expertise and brand's context.

Students learn how to establish effective brand strategies in this elective course, in which three important questions will be answered:

1.  How to establish brand equity
2.  How to quantify brand equity
3.  How to expand your firm with brand equity

This course fundamental aims are to understand:

1.  Important issues in designing and evaluating brand strategies
2.  Appropriate concepts and procedures to increase the long-term profitability of brand strategies.

It includes lectures, exercises, case discussions, and a brand audit assignment. The course content is relevant for students pursuing various professional goals (marketing, consulting, entrepreneurship, etc.) in any type of firm (public or private, large or small, etc.).

<br>

# Student Evaluation

Consider

| Components          | Points |
|---------------------|--------|
| Exam (2)            |        |
| Brand Audit Project | 600    |
| Case Discussions    |        |
| Attendance          | 50     |
| Participation       | 50     |
| Weekly Quiz         |        |
| Total               | 1000   |

Extra Credit: 3-5%

| Letter Grade | Range | To  |
|--------------|-------|-----|
| A            | 100%  | 94% |
| A-           | \<94% | 90% |
| B+           | \<90% | 87% |
| B            | \<87% | 84% |
| B-           | \<84% | 80% |
| C+           | \<80% | 77% |
| C            | \<77% | 74% |
| C-           | \<74% | 70% |
| D+           | \<70% | 67% |
| D            | \<67% | 64% |
| D-           | \<64% | 61% |
| F            | \<61% | 0%  |

<br>

## Attendance, Participation, and Professionalism

Case analyses: 1-2 students will be randomly called to lead off a case discussion.

-   This class meets in-person at the scheduled time slot. Students are expected to be present at all class sessions and to participate by asking and answering questions at multiple points during each class session. In other words, attendance is **mandatory**. Failure to do so will result in loss of class participation and attendance points. Both quality and quantity of contributions are considered in assigning the class participation grade.

-   To be excused due to illness, the student must either notify the professor before class of the illness, or provide the instructor with **a doctor's note**.

-   [Be on time to class]{.underline}. Important material is covered in the first few minutes of class. Students who are late to class will lose attendance points.

-   Students are expected to be prepared and to read assigned discussion cases before class begins. Students are also expected to pay attention in class, and will be called upon to present their views on class material and discussion cases. Students are also expected to contribute to the class by asking questions. Both quality and quantity of contributions are considered in assigning the class participation grade**.**

-   Professional behavior is expected of all students. Professionalism includes being on time, being courteous to class members and the instructor, being reliable and conscientious when working on group projects, and other aspects of behavior normally expected of students or employees.

### Attendance

-   Everyone is allowed to have **one absence** no questions ask. After that, each absence will cost you 50% of the attendance score unless excused by the instructor. Thus, **on your third absence**, all your attendance points will be gone.

-   iClicker attendance will be run automatically from 6:25 PM to 6:40 PM (UTC-06:00) Central Time (US & Canada) on class days.

-   **Attendance points are recorded by iClicker.**

### Participation

-   Your participation points are also recorded by **iClicker in class polls**.

-   Students who are late to class will be marked **absent**, but can still earn participation points.

-   We have 25 class sessions, and each class participation can earn you 2 points, in total 50 participation points.

-   You need to respond to **at least 75% of the questions to earn participation points**.

-   **For each correct response, you can earn 1 point extra credit.** (This can add up!!!)

-   The start and end times for the class are determined by the classroom clock, not the time on students' phones.

<br>

### IClicker Reef {.unnumbered}

-   Please create an account on iClicker App in Apple or Android store with your full name on the Myzou. If you don't have a smart phone, you can do so through desktop version.

-   Once you have successfully downloaded the app and signed in, search for "University of Missouri Columbia"

-   Then search for "**Marketing Research 4050 "** for your course. And select the course by"**Mike Nguyen**"

-   Click **"Add This Course".**

-   You attendance, in class participation, and quiz will be done through the iClicker.

<br>

## Assignments

-   Assignments are to be turned in using Canvas and are due at the time noted on Canvas.

-   Late assignments are eligible for up to 50% of total points if they are turned in within 24 hours of the due date; after that, no credit will be given for late assignments. To be considered, any requests to re-grade an assignment must be made within **one week after the grade has been posted on Canvas**.

Assignments consist of:

-   [Weekly Quizzes]
-   [Case Discussions]
-   [Group Term Project (Project Assignment)](#group-term-project-project-assignment)

<br>

### Weekly Quizzes

-   Each week you will have to complete a quiz on Canvas that is due on Sunday evening (11:59 PM). Students can view correct answers after the due date.

-   The quiz will cover class materials and chapter readings. It's very important that you read the chapter before taking the quiz.

-   You can use your notes during quizzes, but you can't search for answers online (Lockdown browser).

-   There will be 10 questions to be completed in 30 minutes.

-   Students will have 2 attempts to take the quiz and only the higher score of the two will be taken as the final quiz grade

-   These questions are randomly selected from a test bank. Hence, no two quizzes will be the same to prevent students from cheating. Hence, 2 attempts from a student will be different as well.

-   Weekly quiz only goes up until week 12, which means you will only need to do 12 quizzes

-   **No extensions whatever will be granted**.

<br>

### Case Discussions

-   ***Case Discussions*** are [individual]{.underline} exercises to be completed on your own and form the basis for our class discussions.

-   They need to be completed before class meets, and you will be called upon at various times throughout the semester to discuss your work on these exercises.

-   This is a chance for you to apply marketing research materials to real-life settings.

-   Each case study is 20 points. There are a total of 6 cases.

-   Please read the "[Case Discussions Document](https://github.com/mikenguyen13/mar4050_S22/raw/main/case_discussion/case_discussion.pdf)" for more information.

<br>

### Group Term Project (Brand Audit Assignment) {#group-term-project-project-assignment}

A team can have up to 5 members.

Each group will examine a different brand (can consult Interbrand list).

1.  Brand inventories: (a comprehensive summary of a firm's current marketing and branding programs) Brand definition: Brand in consumer's mental map
2.  Brand exploratories (consumer profiles)
3.  Summary and evolution of current branding program.
    1.  How was the brand established? (e.g., brand story, 4Ps, online presence)

    2.  How did the brand grow? (e.g., extension, cobranding, etc.)

    3.  SWOT analysis

Brand Inventory:

-   A detailed profile of how a firm markets, brands, and sells its products and services.

-   Examine all brand elements (e.g., logos, symbols, packaging, slogans, trademarks).

-   Examine the product/idea/service inherent attributes (4Ps)

-   Examine direct and indirect competitive brands for points of parity and points of difference

Brand Exploratory: Consumer knowledge of the brand awareness, associations (category, use, brand promise). This report is to understand what consumers think and feel about the brand to identify sources of brand equity.

-   Analysis of prior research (internal, external) and media (trade magazines, PR sources, employee interviews)

-   Qualitative research (from classmates) and exploratory quantitative survey to develop metal map of brand knowledge.

Recommendations for brand positioning

-   How to move the current brand image to desired brand image? Which new associations to create and which ones to eliminate?

-   Identify a marketing strategy/ program to bring about the desired positioning. How can brand equity be generated and exploited to optimize profits?

Reports:

1.  Progress Report: This report should establish your preliminary vision of a brand's "mental map" in terms of the strength, favorability, and originality of prominent brand connections and propose a brand exploration questionnaire.
2.  Final Report: Your written summary should be 20 double-spaced typed pages, with a one-page executive summary and appendices (1" margins, 12-point font). Each team will deliver a 25-minute brand audit in the last two weeks of the semester. On the day of the presentation, I'd also like the slides.

Similar to company's projects, group projects in academics can be frustrating (e.g., scheduling issues, unequal division of labor, free-rider problem, etc.). However, it's important that you learn how to handle teamwork. Since you can choose your team members, do so wisely! Excellent oral, written, and interpersonal skills are critical for this project. The first component of your Brand Audit includes data collecting, so consider adding at least one marketing research analyst (i.e., those who can conduct data analysis) to your team.

All concerns outside of the intersection between group project works and course content (e.g., contribution quality or member participation) must be addressed internally.

There will be two group evaluations throughout the semester (mid-term and final evaluations). Your individual group project grade will be adjusted based on your team member' evaluations to ensure fairness and professionalism.

Group members will evaluate each other's performance on the project, and the evaluation will be considered in assigning individual students' grades for the project. If a group member consistently fails to contribute appropriately to the group's work, the other group members may request in writing to the instructor that the non-performing member be terminated from group. In such instances, the terminated group member will be allowed to use data collected by the group but will be required to complete remaining project assignments on his/her own, including data analysis, presentation, and final report. A terminated group member may appeal this decision to the instructor in writing, but must do so within **four calendar days of notice of dismissal**.

-   ***Project Assignments*** (PA) are described in a separate document tilted "[Project Assignment](https://github.com/mikenguyen13/mar4050_S22/raw/main/project_assignment/Project_Assignments_online.pdf)". They are to be completed by group members and turned in on the due dates shown. To be considered, any requests to re-grade an assignment must be made within **one week after the grade has been posted on Canvas.**
-   [Sample term project report](https://github.com/mikenguyen13/mar4050_S22/tree/main/project_assignment/written_report)
-   Sign-up [here](https://docs.google.com/spreadsheets/d/1_dxqG99lQMBNp_87SlojglrzqVy6KK4FA4T4SBZ88rE/edit?usp=sharing)

### Branding Insights

#### Branding Insights #1: Brand Perceptions

List 5 things that first come to mind for your favorite brand.

#### Brand Insights #2: Brand Extensions

-   Find the most inappropriate or ineffective brand extension in your opinion, and be ready to defend why it is.

-   Include a relevant picture, advertisement, or item to class

-   The winner of the worst brand extension based on in-class votes will receive a gift certificate.

<br>

### Journal Article Reading

Since academic journal materials can take some time to migrate to textbooks (e.g., about 3-10 years), it's best to stay on top of emerging topics in branding by reading seminal journal articles. Even though you are not expected to fully understand the statistical methods, experiments, or the whole background literature, you are expected to understand the key objectives and major findings when reading articles.

A typical approach to reading journal articles is

1.  understand the study's motivation by reading the introduction and literature review

2.  skim through the method and results section

3.  read the discussion and conclusion section to understand the implications of the study

4.  write a short summary (for the exams)

Articles

-   [@john2006]

-   [@aaker1997b]

-   [@aaker1990]

-   [@völckner2006]

## Examinations

-   Examinations will be multiple choice questions.
-   Makeup exams will be given only in cases of verified illness or in other extenuating circumstances approved at least one week beforehand by the instructor. Makeup exams are normally given during final exam week. An unexcused absence from an exam will result in a grade of zero for that exam.
-   You can use your notes during exams, but you can't search for answers online (Lockdown browser).

<br>

# **TENTATIVE SCHEDULE**

**Import note:**

-   All of the course materials are published on Canvas
-   PA is a group project assignment.
-   CD is case discussion
-   Chapters refers to chapters in the textbook.
-   This schedule is subject to changes due to possible adaption to the class' pace. Hence, you should always view the most updated version on Canvas.
-   This schedule is made based on [2022-2023 Academic Calendar](https://www.registrar.pitt.edu/calendars)

+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| Week | **Date**             | **Topic**                                               | **Assignments Due**                                                                                                                                                                                                                                                                           | **Chapter Reading** |
+:====:+======================+=========================================================+===============================================================================================================================================================================================================================================================================================+=====================+
| 1    | Aug 29               | Course Introduction                                     | Student Information Due                                                                                                                                                                                                                                                                       | 1                   |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Recommended Readings:                                                                                                                                                                                                                                                                         |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@zaltman1997]                                                                                                                                                                                                                                                                            |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
|      | Sep 5                | No class                                                |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      | (Labor Day)          |                                                         |                                                                                                                                                                                                                                                                                               |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 2    | Sep 12               | Customer-based Brand Equity                             | Case: Nike                                                                                                                                                                                                                                                                                    | 2                   |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | Brand Positioning                                       | Brand selection                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Group Formation Announcement                                                                                                                                                                                                                                                                  |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Blog Brand Choice Submission                                                                                                                                                                                                                                                                  |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Recommended readings:                                                                                                                                                                                                                                                                         |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [Aaker (2003)](https://www.researchgate.net/profile/Ann-Mirabito/publication/237251161_MITSloan/links/0a85e53a8aab1063c2000000/MITSloan.pdf)                                                                                                                                              |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 3    | Sep 19               | Brand Resonance & Value Chain                           | Draft brand image survey by the end of class                                                                                                                                                                                                                                                  | 3                   |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | Brand Communities                                       | Case: MTV                                                                                                                                                                                                                                                                                     |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Required readings:                                                                                                                                                                                                                                                                            |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@muniz2001]                                                                                                                                                                                                                                                                                  |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@mcalexander2002]                                                                                                                                                                                                                                                                            |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 4    | Sep 26               | Brand Elements (e.g., names, logos, slogans, packaging) | Project Discussion part 1: STP                                                                                                                                                                                                                                                                | 4                   |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Brand Strategy - Marketing Programs                                                                                                                                                                                                                                                           |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Blog Assignment #1                                                                                                                                                                                                                                                                            |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Case: Target                                                                                                                                                                                                                                                                                  |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 5    | Oct 3                | Marketing Programs (Product, Pricing, Channel)          | Case: Redbull                                                                                                                                                                                                                                                                                 | 5                   |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 6    | Oct 10               | IMC (Promotion)                                         | Case: got milk?                                                                                                                                                                                                                                                                               | 6                   |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Project Discussion Part 2: Brand Elements                                                                                                                                                                                                                                                     |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 7    | Oct 17               | Branding in the Digital Era                             | Case: Intel                                                                                                                                                                                                                                                                                   | 7, 8                |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | Brand Associations                                      | Required reading:                                                                                                                                                                                                                                                                             |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@john2006]                                                                                                                                                                                                                                                                                   |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Branding Insight #2                                                                                                                                                                                                                                                                           |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Due: 1-page report outline and team meetings with professor                                                                                                                                                                                                                                   |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 8    | Oct 24               | Brand Equity Measurement and Management                 | Case: Dollar Shave Club                                                                                                                                                                                                                                                                       | 9                   |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 9    | Oct 31               | Sources of BE - Customer Mindset                        | Case: The Hunger Games: Catching Fire: Using digital and social media for brand storytelling                                                                                                                                                                                                  | 10, 11              |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | (Brand Personality)                                     | Required reading:                                                                                                                                                                                                                                                                             |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | Outcomes of BE - Market Performance                     | [@macinnis1991]                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@aaker1997b]                                                                                                                                                                                                                                                                                 |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@coulter2001]                                                                                                                                                                                                                                                                                |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@azoulay2003]                                                                                                                                                                                                                                                                                |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | [@swaminathan2009]                                                                                                                                                                                                                                                                            |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | EVALUATION OF BRANDS:                                                                                                                                                                                                                                                                         |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   Qualitative Methods                                                                                                                                                                                                                                                                       |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   Laddering                                                                                                                                                                                                                                                                                 |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   ZMET                                                                                                                                                                                                                                                                                      |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   Brand maps                                                                                                                                                                                                                                                                                |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   Ethnography                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | Recommended reading:                                                                                                                                                                                                                                                                          |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@aaker1999a]                                                                                                                                                                                                                                                                             |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [Zaltman, Coulter and Hige (1995)](https://www.researchgate.net/profile/Robin-Coulter/publication/235361006_Seeing_the_Voice_of_the_Customer_Metaphor-Based_Advertising_Research/links/55b7675508aed621de045f0a/Seeing-the-Voice-of-the-Customer-Metaphor-Based-Advertising-Research.pdf) |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [Berrry, Carbone & Haeckel (2002)](https://www.researchgate.net/profile/Lewis-Carbone/publication/281994011_How_to_Lead_the_Customer_Experience/links/5b35cc65aca2720785f49681/How-to-Lead-the-Customer-Experience.pdf?_sg%5B0%5D=started_experiment_milestone&origin=journalDetail)      |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 10   | Nov 7                | Brand Design and Implementation (Brand Architecture)    | Case: Nivea                                                                                                                                                                                                                                                                                   | 12, 13              |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | New Product Development and Brand Extensions            | -   [@aaker1990]                                                                                                                                                                                                                                                                              |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@kirmani1999]                                                                                                                                                                                                                                                                            |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@swaminathan2001]                                                                                                                                                                                                                                                                        |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@bottomley2001]                                                                                                                                                                                                                                                                          |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@balachander2003]                                                                                                                                                                                                                                                                        |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@völckner2006]                                                                                                                                                                                                                                                                           |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@swaminathan2009a]                                                                                                                                                                                                                                                                       |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         | -   [@swaminathan2011]                                                                                                                                                                                                                                                                        |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 11   | Nov 14               | Sustainable Branding                                    | Case: Snapple                                                                                                                                                                                                                                                                                 | 14                  |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | Revitalizing diluted brands                             |                                                                                                                                                                                                                                                                                               |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
|      | Nov 21               | No class                                                |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      | (Thanksgiving break) |                                                         |                                                                                                                                                                                                                                                                                               |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 12   | Nov 28               | 4 presentations                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      | Discussion + Lecture                                    |                                                                                                                                                                                                                                                                                               |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 13   | Dec 5                | 4 presentations                                         |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      | (Last day of class)  | Discussion + Lecture                                    |                                                                                                                                                                                                                                                                                               |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+
| 14   | Dec 12               | Final Exam                                              |                                                                                                                                                                                                                                                                                               |                     |
|      |                      |                                                         |                                                                                                                                                                                                                                                                                               |                     |
|      | (Final Exam Week)    |                                                         |                                                                                                                                                                                                                                                                                               |                     |
+------+----------------------+---------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+---------------------+

: Tentative Schedule

<br>

# Academic Honesty

Academic honesty is fundamental to the activities and principles of a university. Students are expected to comply with the [University of Pittsburgh's Policy on Academic Integrity.](https://www.provost.pitt.edu/faculty/academic-integrity-freedom/academic-integrity-guidelines) All members of the academic community must be confident that each person's work has been responsibly and honorably acquired, developed, and presented. Any incident of academic honesty (such as cheating on tests or plagiarism) will be reported to the office of the provost. Academic dishonesty is an extremely serious matter with serious consequences, potentially including an automatic F for the course and probation or expulsion.

<br>

# Special Needs

If you have special needs as addressed by the Americans with Disabilities Act and need assistance, you must notify the instructor by the second week of the semester. To request academic accommodations, students must also register with the Disability Resources and Services, 216 William Pitt Union, (412) 648-7890. It is the campus office responsible for reviewing documentation provided by students requesting academic accommodations, and for accommodations planning in cooperation with students and instructors, as needed and consistent with course requirements.

<br>

# Policy on Discrimination

*We have **no tolerance** for discrimination or acts of hate in our community and encourage robust, respectful dialogue and interactions. No matter where you come from, no matter your race, gender, identity, preference or idea & perspective, we all come together to learn, and everyone deserves to be treated with respect and to thrive. If anyone experiences discrimination or harassment, we encourage them to report it to our campus [Office for Equity, Diversity, and Inclusion](https://www.diversity.pitt.edu/civil-rights-title-ix-compliance).*

<br>

# **Decreasing the Risk of COVID-19 in Classrooms**

Students must follow public health legislation and University of Pittsburgh health standards and recommendations during the epidemic. While in class, you must wear a facial covering and comply with physical distance restrictions; the University may impose more requirements during the semester. These guidelines protect everyone's health and safety. Failure to meet these requirements may result in a Student Conduct violation. Please review these resources:

-   [Community Wide Compliance](https://www.coronavirus.pitt.edu/cmro/community-wide-compliance) from Dr. Kenyon Bonner, Vice Provost and Dean of Students

-   [Pitt Community Compact](https://www.coronavirus.pitt.edu/pitt-community-compact)

-   [Culture and Compliance](https://www.coronavirus.pitt.edu/return-campus/culture-and-compliance) page that lists ways to support a culture of Health and Safety

For the most up-to-date information and guidance, please visit [coronavirus.pitt.edu](https://www.coronavirus.pitt.edu/) and check your Pitt email for updates before each class.

\newpage

# References
