---
title: "Case Studies"
author: "Mike Nguyen"
date: "`r Sys.Date()`"
output: pdf_document
---

Based on the Best Practice Cases in Branding, Strategic Brand Management

To purchase the case studies, use this [link](https://console.pearsoned.com/enrollment/maumcs)

# Snapple: Revitalizing a Brand

In the 1980s, many "alternative" soft drink brands were created for New York's yuppies, but only Snapple succeeded. Quaker bought it for \$1.7 billion and sold it to Triarc for \$300 million four years later. Can we understand Quaker's problems and advise Triarc's Mike Weinstein on how to reverse a trendy brand that was out of fashion with its sales decline.

This case follows Snapple's 26-year history. It chronicles the brand's genesis, its struggle to prevent extinction at birth, its victory, a \$1.4 billion tragedy, and its attempt to rebuild.

Snapple was an American success story that lost its way and rediscovered itself over 20 years. Snapple entered the soft drink industry in the 1980s. It was the first alternative beverage to challenge Coke and Pepsi. It wasn't a soda, therefore it was innovative. Using glass bottles and a hot fill procedure, Snapple was made without preservatives. The outcome was "Best Stuff on Earth" product and brand. Snapple has a joyful, quirky image.

Discussion Questions

1.  Why did Snapple thrive from 1972 to 1993 when many premium fruit drink startups failed? Consider 4 Ps

2.  Did Quaker make a mistake by purchasing Snapple, or were they mismanaged from 1994 to 1997?

3.  From 1998 onward, what lessons can Triarc's managers learn from Quaker's experience? What is Snapple target market? Should Snapple mean different things to different people? What are the dangers and advantages of leaving "what the brand stands for" open to customer interpretations? Can we say that Snapple is a fashion brand?

4.  Snapple's brand image and equity sources.

5.  Quaker's mistake: What did they do wrong?

6.  Was Triac's marketing successful and appropriate?

7.  How would Cadbury's purchase of Snapple effect its equity?

8.  How should Cadbury handle Snapple? Should Snapple grow or change?

Materials:

-   [Summary by HBR](https://hbr.org/2002/01/how-snapple-got-its-juice-back)

-   [Snapple Best Stuff](https://vimeo.com/224722185)

# The Hunger Games: Catching Fire

1.  What is the difference between The Hunger Games' marketing campaign and a traditional one for a movie?
2.  Critique the brand storytelling aspect of the marketing campaign based on persistence, pervasiveness, participation, and personalization.
3.  Examine Lionsgate's decision to focus on current fans instead of new ones. Why do you agree or disagree with this decision?
4.  What did the campaign do well and what could it have done better?
5.  For the sequel, what aspect of the campaign would you continue to use and what aspect would you leave out?
6.  In what ways might non-entertainment items be marketed using the transmedia storytelling strategy? Do you think brand storytelling is the future of the entertainment industry or it was a one-hit wonder?

Materials:

-   Document

-   [News](https://www.minttwist.com/blog/catching-fire-a-hunger-games-digital-marketing-case-study/)

# Rebranding DSM: creating Sustainable Shared Value

1.  Why and how did DSM redesign their brand?
2.  What modifications were made to the brand architecture?
3.  How did the DSM determine its success?
4.  How can DSM address future challenges?
5.  Consider the function of sustainability as a company branding factor.

# McDonald's and the Hotel Industry

1.  Can the McDonald's brand franchise be utilized in the hotel industry? Which components are not exploitable?
2.  Describe McDonald's brand identity and its core. Is there a distinction between adult and children segments?
3.  Consider the six components outlined for hotel and accommodation in the case. Considering McDonald's brand identification and the competition, which hotel sector segment(s) would make the most sense for McDonald's to enter?
4.  Based on your findings, develop a hotel concept for McDonald's. What is the positioning of the brand?

# Burberry

Burberry lost brand equity and was diluted over time, like many other great brands. Changes in customer preferences, competition, and brand marketing programs (product, pricing, promotion, and distribution) cause these circumstances. However, Rose Marie Bravo was able to revamp the brand.

1.  The fashion business is inherently hazardous due to demand fluctuations. What modifications did Rose Marie Bravo implement? Have these modifications raised or reduced the risk?
2.  How has the Team succeeded in enhancing the prominence of the Burberry brand?
3.  Should Burberry shift towards a more limited usage of the check? How will this influence the sustainability of the brand?
4.  What is Burberry's customer base? How may Burberry's non-target popularity harm the brand? How can the brand combat this?
5.  Should Burberry launch Brit? And why?

# Dollar Shave Club - Brand Story

Additional Materials:

-   [Linx's summary video](https://www.youtube.com/watch?v=QdlZory4hOs)

# MTV: Building Brand Resonance

MTV was founded in 1981 as a cable pioneer. Over the following 20 years, MTV became the center of pop culture worldwide. This case covers MTV's journey from humble beginnings to worldwide media network.

Discussion Questions:

1.  Explain MTV's past and present brand equity. What's changed?
2.  How has the Internet impacted MTV's branding? How should MTV's strategy adapt because of the internet's changing role?
3.  What is MTV's brand portfolio? How have sister networks influenced its brand equity? How would you position sibling networks to increase MTV's equity?

# Clorox: Positioning the Clorox toilet Wand System

In April 2004, Clorox will unveil its sixth toilet cleaning method. This case examines how Clorox should position its late-entry product.

1.  Should Clorox join the market for toilet cleaning systems?
2.  Who should be the Clorox ToiletWand's intended market?
3.  Determine the ToiletWand's competitive context; how should it be positioned in respect to its competitors?
4.  Which benefit of the ToiletWand is most valuable to the intended consumer?
5.  In its marketing plan, what should ToiletWand identify as its unique selling proposition?
6.  Create a positioning statement.
7.  Create a strategic statement.

# Nivea: Managing a Global Brand Hierarchy

Nivea, the world's largest cosmetics brand, has guarded its position in Europe for a decade. The corporation grew throughout South and Latin America, Eastern Europe, and Asia. Nivea was global by the late 1990s. Nivea expanded its product offerings by entering new markets and creating new subbrands. In this scenario, we'll explore how Nivea has grown while maintaining strong brand connotations.

1.  How did Nivea succeed? Determine their marketing program's success factors.
2.  What's Nivea's brand equity? Which items help maintain equity?
3.  How does the Nivea umbrella brand compare to various product brands? How should Nivea handle its hierarchy?

# Ralph Lauren

Ralph Lauren is a world-renowned brand known for its design, elegance, and quality. Ralph Lauren offers items for men, women, children, and home furnishings, unlike many other high fashion labels. How does this corporation handle so many goods without dilution?

1.  Compare Ralph Lauren's market position to rivals'. Their long-term position? Why?
2.  Ralph Lauren Polo has various brands, collections, platforms, and licensees. How do these factors fit into Ralph Lauren's business model?
3.  How can brand image be correctly transmitted through retail shop relationships?
4.  Does POLO's premium image suffer when sold at Costco?
5.  Why should RL add future extensions? What Ralph Lauren extensions wouldn't work, and why?
6.  Is the brand protected if the man can't run the company?

# Brand Extension

## KFC's Nail Polish

-   Is this a natural brand extension for KFC? Is this product consistent with KFC's core identity?

-   Is any publicity good publicity? (e.g., [200 mil online views](https://america.cgtn.com/2016/05/20/kfc-nail-polish-campaign-causes-stir-on-hong-kong-social-media))

Materials:

-   [The Branding Journal](https://www.thebrandingjournal.com/2016/05/finger-lickin-good-kfc-nail-polish-product-launch/)

-   [Video](https://www.youtube.com/watch?v=975JZw3khP8&ab_channel=HongKongBeatbox%28HKB%29)

-   [BBC News](https://www.bbc.com/news/world-asia-china-36220142)
