---
title: "Brand Audit"
author: "Mike Nguyen"
date: "`r Sys.Date()`"
output: pdf_document
---

| Task                                   | Points |
|----------------------------------------|--------|
| [Group Formation]                      | 10     |
| [Team Orientation and Brand Selection] | 10     |
| [Brand Exploratory]                    | 20     |
| [Brand Positioning]                    | 20     |
| [Brand Elements]                       | 20     |
| [Brand Strategy - Pricing]             | 20     |
| [Brand Strategy - Promotion]           | 20     |
| [Mid-term Evaluation]                  | 5      |
| [Progress Report]                      | 20     |
| [Project Presentation]                 | 60     |
| [Presentation Critique]                | 10     |
| [Project Report]                       | 80     |
| [Final Evaluation]                     | 5      |
| Total                                  | 300    |

\newpage

# Group Formation

-   Your group will work together extensively throughout the semester to complete a term project.

-   There can be up to 5 members per group.

-   You may

    -   choose the members of your group or

    -   have the instructor assign you to a group. Group assignments done by the instructor will be on a random basis.

-   During the first class session, there will be small group breakout that will allow you to get to know some of your classmates

Submit this assignment on Canvas and indicate

-   Title your assignment word document file name with "**Group & team captain's initials**" if you and three or four other classmates have formed a team. For example, if your team captain is Michael Jordan then you will title your word document as 'Group MJ.' In the word document to be submitted, please include the identity of your teammates, including your name in descending order of the first name

-   Title your assignment word document file name with "**Random & your initials**" if you would like the instructor to assign you to a team

This assignment needs to be submitted individually by each student in the class.

# Team Orientation and Brand Selection

Your group should submit the two items below on Canvas.

**(1)** Completed [Team Orientation Assignment](https://github.com/mikenguyen13/mar4050_S22/raw/main/project_assignment/Team%20Orientation.docx)

**(2)** Your group's brand choice for the project

# Brand Exploratory

-   Consumer profiles: who are the current target consumers for your brand?

-   Consumer's mental map of the brand: consumer knowledge of the brand awareness, associations (e.g., category, use, brand promise). This report is to understand what consumers think and feel about the brand to identify sources of brand equity.

Sources to develop your brand mental map:

-   Analysis of prior research (internal, external) and media (trade magazines, PR sources, employee interviews)

-   Qualitative research (from classmates) and possibly an exploratory quantitative survey to develop a metal map of brand knowledge.

Each group is expected to submit a two-page double-spaced word or pdf document.

# Brand Positioning

Summary of the positioning of the brand.

A comprehensive summary of a firm's current marketing and branding programs

-   Current market: A detailed profile of how a firm markets, brands, and sells its products and services.
-   Examine the product/idea/service inherent attributes (4Ps)
-   Current Competition: Examine direct and indirect competitive brands for points of parity and points of difference
-   Students are encouraged to incorporate these factors into a comprehensive SWOT analysis. However, this is not mandatory.

Recommendations for brand positioning

-   Identify the target market that would be willing to pay for the proposed positioning

-   How to move the current brand image to the desired brand image? Which new associations to create and which ones to eliminate?

Each group must submit a 5-page double-spaced word or pdf document.

# Brand Elements

-   Critically examine all brand elements of your chosen brand (e.g., logos, symbols, packaging, slogans, trademarks).

Each group is expected to turn in a 2-page double-spaced report.

# Brand Strategy - Pricing

-   Since you have the brand positioning, target market, and elements in place, it is time to put together a brand strategy.  This section focuses on pricing where each team is required to come up with a pricing strategy.  It includes the base prices, special pricing programs, bundle packages, and season ticket pricing.

-   Keep in mind that pricing is a powerful tool for branding. Use your imagination and creativity to formulate a pricing strategy that can strengthen your brand equity.

Each team is expected to turn in a 1-page double-spaced report.

# Brand Strategy - Promotion

-   In this section, you are asked to put together a promotion campaign for your brand.  You can take advantage of various promotional programs such as advertising, sales promotions, events and sponsorships, personal selling, and co-branding with strategic partners.

-   Feel free to come up with creative promotion ideas that are outside of the traditional promotional toolbox.  Again, your promotional campaign should be designed around your positioning and target market.

Each team is required to submit a report of at least two pages. Due to the creative nature of this assignment, you can go for a longer report.

# Meeting with instructor

-   Each group will meet with the instructor to go over the project and discuss the [progress report].

-   Your group is expected to explain the progress and the direction you want to go to complete the project, and the instructor will provide feedback and advice on completing the project.

-   The meeting times will be scheduled during class time.

# Mid-term Evaluation

-   In this assignment, you will evaluate your own performance throughout the project and that of other members of your group on the major project assignments completed so far.

-   Click this [link](https://pitt.co1.qualtrics.com/jfe/form/SV_9QtDOayurK08llc) to complete your evaluation.

-   This evaluation will be used to calculate 1/3 of the weight for your final report score, which means you can still have a chance to work hard and make up the work to earn a higher grade.

**Please submit the screenshot of your survey submission.**

The formula to calculate your final report score is

$$
(\text{Mid-term Evaluation} \times \frac{1}{3} + \text{Final Evaluation} \times \frac{2}{3} ) \times \text{Instructor's score for the group}
$$

For example, you are evaluated to have contributed 60% to the project based on the mid-term evaluation. Remember that this is based on theoretical contributions, which means in a group of 5 people, you should contribute theoretically 20% (100%/5) to the overall project, but you are evaluated to contribute 12% to the overall project, then your theoretical contribution is 12%/20% = 60%.

However, you try to make it up and, in the final evaluation, your team evaluates you as having contributed 100% of your efforts to the project (20%/20%). And the instructor assigns 80 points to your group. Then your report score will be

$$
(60\% \times \frac{1}{3} + 100 \% \times \frac{2}{3}) \times 80 \approx 70
$$

This evaluation is confidential and will not be shared with group members. However, if you have a concern about your level of contribution to the project, or the contribution of another group member, you are encouraged to discuss this with your group. Regardless, it is a good time of the semester to take a few minutes of a regularly scheduled group meeting to discuss the following issues:

-   is communication in the group working effectively? Are there ways it could be improved?

-   is everyone doing their fair share of work? Is anyone feeling over-burdened?

-   what significant contributions has each group member made to the project so far?

-   what changes could each group member make to enhance group functioning?

# Progress Report {data-link="Progress Report"}

-   Each group is required to submit a **double-spaced two-page memo** summarizing the progress of the project and the plan for its completion.  It should address the issues raised during the meeting with the instructor earlier and describe the progress and challenges.

-   It would be ideal to have the backbone of the project paper done by this point so that the instructor can provide specific feedback.

# Project Presentation {data-link="Project Presentation"}

[Presentation Evaluation](https://pitt.co1.qualtrics.com/jfe/form/SV_bPGLFQRYFiYFH8y)

This assignment is due the day before your presentation at 11:59 PM.

-   The presentation of your term project should cover the topics described on the [Pointers on Presentations](https://github.com/mikenguyen13/brand_F22/raw/main/project/presentation/Pointers%20on%20presentations.docx).

-   The presentation can be either in PowerPoint format, Google Slides, or Prezi.

-   During the presentation, the monitor at the back of the room will be turned off so that you can get more practice in a setting similar to what you will encounter in a business environment.

-   The presentation should last 25 minutes. If you go under or over this time frame, there is a grade deduction of 1 point per minute. The class will have an opportunity to ask you questions following your presentation (5 minutes).

-   Your presentation will be graded on the criteria described in the "[Presentation Evaluation Form](https://github.com/mikenguyen13/brand_F22/raw/main/project/presentation/Presentation%20Evaluation%20Assignment.pdf)."

-   You are responsible for practicing your presentation on the classroom equipment before presentation day and making sure that everyone in the group is familiar with how the equipment works.

-   On presentation day, you must be set up and ready to go [before]{.underline} the beginning of class. If you are not ready at that time, there will be point deductions and you may be asked to give your presentation at another time. Class time is very tightly scheduled during presentation days, and it is necessary that all groups be ready to present at the appointed time.

The grade for this assignment is based on

-   Presentation submission (20 points)
-   [Instructor's evaluation](https://docs.google.com/spreadsheets/d/1EmvxRjSobmu4Wcl0rrez1PjnlX6ky3J7pRfFn-Hjw1w/edit#gid=0) (20 points)
-   Peers' evaluations (20 points)

# Presentation Critique

Step 1: Familiarize yourself with the details of the critique assignment as described in the "[Presentation Evaluation Form](https://github.com/mikenguyen13/brand_F22/raw/main/project/presentation/Presentation%20Evaluation%20Assignment.pdf)".

Step 2: All teams that are not presenting are required to submit their evaluation (1 evaluation per team for a presenting group). To submit your presentation critique, please fill out [this Qualtrics survey](https://pitt.co1.qualtrics.com/jfe/form/SV_bPGLFQRYFiYFH8y) after each presentation (you can submit the survey multiple times)

# Project Report

Each group must submit a report of at least 15 pages, including one page for an executive summary and one page for appendices (1" margins, 12-point font).

Your brand audit report should be a cohesive compilation of all previous assignments with improvements suggested by the instructor as well as feedback from your presentation. Your group project grade will greatly suffer if you just copy and paste all previous sections.

# Final Evaluation

-   In this assignment, you will evaluate your own performance throughout the project and that of other members of your group on the major project assignments completed so far.

-   Click this [link](https://pitt.co1.qualtrics.com/jfe/form/SV_4GbkPzBwJ0ygKnc) to complete your evaluation.

**Please submit the screenshot of your survey submission.**

**If this form is not submitted, you may receive an incomplete grade for the course.**

The formula to calculate your final report score is

$$
(\text{Mid-term Evaluation} \times \frac{1}{3} + \text{Final Evaluation} \times \frac{2}{3} ) \times \text{Instructor's score for the group}
$$

For example, you are evaluated to have contributed 60% to the project based on the mid-term evaluation. Remember that this is based on theoretical contributions, which means in a group of 5 people, you should contribute theoretically 20% (100%/5) to the overall project, but you are evaluated to contribute 12% to the overall project, then your theoretical contribution is 12%/20% = 60%.

However, you try to make it up and, in the final evaluation, your team evaluates you as having contributed 100% of your efforts to the project (20%/20%). And the instructor assigns 80 points to your group. Then your report score will be

$$
(60\% \times \frac{1}{3} + 100 \% \times \frac{2}{3}) \times 80 \approx 70
$$
